export default {
    MAIL_TRANSPORTER: 'MAIL_TRANSPORTERT',
    MAIL_SENDINBLUE: 'MAIL_SENDINBLUE',
    JWT_SECRET:'secretKey',
    REPO_OPTIONS:'REPO_OPTIONS',
    CUSTOMER_OPTIONS: 'CUSTOMER_OPTIONS'
}